### ISSUE TITLE
Dungeon Role Icon always showing

### ISSUE THREAD

**Issue by Kahuma1** [bkader/Grid2-WoTLK#5]
As the titel says the dungeon role icon is not just showing in a dungeon group but also if you join a raidgroup.
https://ibb.co/2svLJgV

**Comment by bkader** [comment]
The `Role` status is only meant to show **Main Tank** and **Main Assist** while the `Dungeon Role` is meant to only show `Tank`, `Healer` and `Damager` roles when in a dungeon. I will add an option to the the dungeon role to enable using it in a raid group as well. If the option is enabled, the icon will be shown whenever you are in a group and it doesn't matter if you are in an instance or not.

**Comment by Kahuma1** [comment]
Or just make the dungeon role icon only show in 5man groups and not in raids.

**Comment by bkader** [comment]
> Or just make the dungeon role icon only show in 5man groups and not in raids.

I know, I will do that. But the problem is that:
1. Dungeon Roles are: Tank, Healer and Damager.
2. Raid Roles are: Main Tank and Main Assist.

So in the case where a player wants to show the dungeon roles in a raid group, just hiding while not in a dungeon doesn't help. So, adding the option seems to be the best option for now, if disabled, roles won't be shown unless you are in a dungeon. If enabled, roles will be shown in dungeons as well as on raids (_depending on the spec for the latter_).
